# Generated by Django 5.0.4 on 2024-11-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='image',
            field=models.ImageField(max_length=500, upload_to='progress_images/'),
        ),
    ]
