# Generated by Django 5.0.4 on 2024-11-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_progress_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(),
        ),
    ]
