# Generated by Django 5.0.4 on 2024-12-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_alter_progress_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
